Feature: Access the URSA Bank application and create a application for Business Commercial Mortgage

  @Regression
  Scenario Outline: Signup into Customer Portal Application and create a business commercial mortage process
    Given Signup into Customer Portal
      |TestCaseId|LoanType  |FirstName  |MiddleName  |LastName  |Mobile  |
      |<TestCaseId>|<LoanType>|<FirstName>|<MiddleName>|<LastName>|<Mobile>|
    And Enter Eligibility Information for <LoanType>
      |LoanAmount  |LoanPurpose  |LoanTermMonths  |RepaymentTypes  |AmortizedTermMonths  |CaptialRepaymentHolidayMonths  |
      |<LoanAmount>|<LoanPurpose>|<LoanTermMonths>|<RepaymentTypes>|<AmortizedTermMonths>|<CaptialRepaymentHolidayMonths>|
    And Enter Business Information
      |LegalBusinessName  |CRN  |DateOfIncorporation  |ApplicationType  |IndustryDoesBusinessBelongTo  |RegAddress  |RegCity  |RegCntry   |RegPostCode  |TradingAddress   |TradingCity  |TradingCntry   |TradingPostCode  |TotalNoOfProperties  |EstimatedPortfolioValue  |TotalOutstandingMortgageBalance  |TotalMontlyRentalIncome  |TotalMonthlyMortgagePayment  |
      |<LegalBusinessName>|<CRN>|<DateOfIncorporation>|<ApplicationType>|<IndustryDoesBusinessBelongTo>|<RegAddress>|<RegCity>|<RegCntry> |<RegPostCode>|<TradingAddress> |<TradingCity>|<TradingCntry> |<TradingPostCode>|<TotalNoOfProperties>|<EstimatedPortfolioValue>|<TotalOutstandingMortgageBalance>|<TotalMontlyRentalIncome>|<TotalMonthlyMortgagePayment>|
    And Enter Personal Information for <LoanType>
      |Role  |Title  |DateOfAppointment  |Shareholding20OrGreater  |PercentShare  |Nationality  |MaritalStatus  |DOB  |NINumber  |PermanentRightToResideInsideUK  |FromBirth  |LengthOfResidencyYears  |LengthOfResidencyMonths  |PreviousTitle  |PreviousFirstName  |PreviousMiddleName  |PreviousLastName  |HomePhone  |MobileNumber  |MarketingPreference  |ByEmail  |ByTelephone  |BySms  |
      |<Role>|<Title>|<DateOfAppointment>|<Shareholding20OrGreater>|<PercentShare>|<Nationality>|<MaritalStatus>|<DOB>|<NINumber>|<PermanentRightToResideInsideUK>|<FromBirth>|<LengthOfResidencyYears>|<LengthOfResidencyMonths>|<PreviousTitle>|<PreviousFirstName>|<PreviousMiddleName>|<PreviousLastName>|<HomePhone>|<MobileNumber>|<MarketingPreference>|<ByEmail>|<ByTelephone>|<BySms>|
    And Enter Personal Continued Information for <LoanType>
      |ResidentialStatus  |MailingStreet  |City  |Country  |PostCode  |PreviousStreet  |PreviousCity  |PreviousCountry  |PreviousPostCode  |
      |<ResidentialStatus>|<MailingStreet>|<City>|<Country>|<PostCode>|<PreviousStreet>|<PreviousCity>|<PreviousCountry>|<PreviousPostCode>|
    And Enter Security Information
      |SecurityType  |SecurityEstimatedValue  |SecurityPurchasePrice  |SecurityLocation  |SecurityStreetAddress  |SecurityCity  |SecurityCountry  |SecurityPostCode  |SecurityPropertyType  |SecurityPropertyDescription  |SecurityUseOfProperty  |SecurityTenure  |YearsRemainingOnLease  |RentReviewDate  |ServiceCharge  |GroundRent  |
      |<SecurityType>|<SecurityEstimatedValue>|<SecurityPurchasePrice>|<SecurityLocation>|<SecurityStreetAddress>|<SecurityCity>|<SecurityCountry>|<SecurityPostCode>|<SecurityPropertyType>|<SecurityPropertyDescription>|<SecurityUseOfProperty>|<SecurityTenure>|<YearsRemainingOnLease>|<RentReviewDate>|<ServiceCharge>|<GroundRent>|
    And Enter Borrowers & Guarantors Information
      |BorrowerFirstName  |BorrowerLastName  |BorrowerEmail  |BorrowerMbNo  |BorrowerRole  |BorrowerRoleOnLoan  |
      |<BorrowerFirstName>|<BorrowerLastName>|<BorrowerEmail>|<BorrowerMbNo>|<BorrowerRole>|<BorrowerRoleOnLoan>|
    Then Review the Information for <LoanType>
      |LoanType  |LoanAmount  |LoanPurpose  |LoanTermMonths  |RepaymentTypes  |AmortizedTermMonths  |CaptialRepaymentHolidayMonths  |LegalBusinessName  |CRN  |DateOfIncorporation  |ApplicationType  |IndustryDoesBusinessBelongTo  |RegAddress  |RegCity  |RegCntry   |RegPostCode  |TradingAddress   |TradingCity  |TradingCntry   |TradingPostCode  |TotalNoOfProperties  |EstimatedPortfolioValue  |TotalOutstandingMortgageBalance  |TotalMontlyRentalIncome  |TotalMonthlyMortgagePayment  |Role   |Title  |DateOfAppointment  |shareholding20OrGreater  | PercentShare   |Nationality  |MaritalStatus  |DOB  |NINumber   |PermanentRightToResideInsideUK  |FromBirth  |LengthOfResidencyYears  |LengthOfResidencyMonths  |PreviousTitle  |PreviousFirstName  |PreviousMiddleName  |PreviousLastName  |HomePhone   |MobileNumber   |MarketingPreference  |ByEmail  |ByTelephone  |BySms  |ResidentialStatus   |MailingStreet  |City   |Country  |PostCode  |PreviousStreet  |PreviousCity  |PreviousCountry  |PreviousPostCode  |SecurityEstimatedValue  |SecurityPurchasePrice  |SecurityLocation  |SecurityStreetAddress  |SecurityCity  |SecurityCountry  |SecurityPostCode  |BorrowerFirstName  |BorrowerLastName  |BorrowerRoleOnLoan  |
      |<LoanType>|<LoanAmount>|<LoanPurpose>|<LoanTermMonths>|<RepaymentTypes>|<AmortizedTermMonths>|<CaptialRepaymentHolidayMonths>|<LegalBusinessName>|<CRN>|<DateOfIncorporation>|<ApplicationType>|<IndustryDoesBusinessBelongTo>|<RegAddress>|<RegCity>|<RegCntry> |<RegPostCode>|<TradingAddress> |<TradingCity>|<TradingCntry> |<TradingPostCode>|<TotalNoOfProperties>|<EstimatedPortfolioValue>|<TotalOutstandingMortgageBalance>|<TotalMontlyRentalIncome>|<TotalMonthlyMortgagePayment>|<Role> |<Title>|<DateOfAppointment>|<shareholding20OrGreater>| <PercentShare> |<Nationality>|<MaritalStatus>|<DOB>|<NINumber> |<PermanentRightToResideInsideUK>|<FromBirth>|<LengthOfResidencyYears>|<LengthOfResidencyMonths>|<PreviousTitle>|<PreviousFirstName>|<PreviousMiddleName>|<PreviousLastName>| <HomePhone>|<MobileNumber> |<MarketingPreference>|<ByEmail>|<ByTelephone>|<BySms>| <ResidentialStatus>|<MailingStreet>|<City> |<Country>|<PostCode>|<PreviousStreet>|<PreviousCity>|<PreviousCountry>|<PreviousPostCode>|<SecurityEstimatedValue>|<SecurityPurchasePrice>|<SecurityLocation>|<SecurityStreetAddress>|<SecurityCity>|<SecurityCountry>|<SecurityPostCode>|<BorrowerFirstName>|<BorrowerLastName>|<BorrowerRoleOnLoan>|

#    And Submit the Application

    Examples:
      |TestCaseId|FirstName|MiddleName|LastName|Mobile    |LoanType                   |LoanAmount |LoanPurpose |LoanTermMonths  |RepaymentTypes        |AmortizedTermMonths  |CaptialRepaymentHolidayMonths  |LegalBusinessName    |CRN     |DateOfIncorporation|ApplicationType |IndustryDoesBusinessBelongTo |RegAddress             |RegCity        |RegCntry |RegPostCode|TradingAddress|TradingCity     |TradingCntry  |TradingPostCode|TotalNoOfProperties|EstimatedPortfolioValue|TotalOutstandingMortgageBalance|TotalMontlyRentalIncome|TotalMonthlyMortgagePayment|Role             |Title|DateOfAppointment|Shareholding20OrGreater|PercentShare |Nationality|MaritalStatus|DOB      |NINumber |PermanentRightToResideInsideUK|FromBirth|LengthOfResidencyYears|LengthOfResidencyMonths|PreviousTitle|PreviousFirstName|PreviousMiddleName|PreviousLastName| HomePhone|MobileNumber|MarketingPreference                                                              |ByEmail  |ByTelephone  |BySms|ResidentialStatus     |MailingStreet |City      |Country       |PostCode|PreviousStreet |PreviousCity      |PreviousCountry       |PreviousPostCode|SecurityType               |SecurityEstimatedValue|SecurityPurchasePrice|SecurityLocation|SecurityStreetAddress|SecurityCity|SecurityCountry|SecurityPostCode|SecurityPropertyType          |SecurityPropertyDescription|SecurityUseOfProperty|SecurityTenure|YearsRemainingOnLease|RentReviewDate|ServiceCharge|GroundRent|BorrowerFirstName |BorrowerLastName |BorrowerEmail|BorrowerMbNo |BorrowerRole     |BorrowerRoleOnLoan|
      |TP-13     |Manish   |Kumar     |Gupta   |9990933804|Business Commercial Mortgage|1000       |Refinance   |120             |Interest Only         |100                  |90                             |    Testing          |12345678|1/1/2018           |Corporation     |Technology                   |Three Cherry Trees Lane|Hemel Hempstead|Herts    |HP2 7AH    |Arndale House |Manchester      |United Kingdom|M4 3AQ         |2                  |50000                  |1000                           |20000                  |1200                       |Business Partner |Test |5/9/2018         |Yes                    |30           |British    |Married      |5/1/2000 |1239087  |YES                           |Yes      |10                    |2                      |Mr           |Ajay             |Kumari            |Pant            |23123123  |72012390    |Yes please, send me information about Revver products and services               |Yes      |Yes          |Yes  |Owner with Mortgage   |Testing Street|Manchester|United Kingdom|M44AX   |Pre Street     |Pre City          |Germany               |M44EX           |Commercial - Industrial    |4000                  |2000                 |England         |Rohini               |Delhi       |India          |243003          |Office                        |Executive                  | Investment          |Freehold      |20                   |5/26/2019     |100          |200       |Andrew	        |Chatterton       |abc@gmail.com|07587278018  |Business Partner |	Guarantor      |