Feature: Access the URSA Bank application and create a application for Business Commercial Mortgage

  @Regression
  Scenario Outline: Login into Customer Portal Application with defafult credential and create a business commercial mortage process using Data Driven

    Given Login into 'Customer Portal' application for the <TestCaseId>
    When Navigate to Marketplace
    And Apply for <LoanType>
    And Enter Eligibility Information for <LoanType>
      |LoanAmount  |LoanPurpose  |LoanTermMonths  |RepaymentTypes  |AmortizedTermMonths  |CaptialRepaymentHolidayMonths  |
      |<LoanAmount>|<LoanPurpose>|<LoanTermMonths>|<RepaymentTypes>|<AmortizedTermMonths>|<CaptialRepaymentHolidayMonths>|
    And Enter Business Information
      |LegalBusinessName  |CRN  |DateOfIncorporation  |ApplicationType  |IndustryDoesBusinessBelongTo  |RegAddress  |RegCity  |RegCntry   |RegPostCode  |TradingAddress   |TradingCity  |TradingCntry   |TradingPostCode  |TotalNoOfProperties  |EstimatedPortfolioValue  |TotalOutstandingMortgageBalance  |TotalMontlyRentalIncome  |TotalMonthlyMortgagePayment  |
      |<LegalBusinessName>|<CRN>|<DateOfIncorporation>|<ApplicationType>|<IndustryDoesBusinessBelongTo>|<RegAddress>|<RegCity>|<RegCntry> |<RegPostCode>|<TradingAddress> |<TradingCity>|<TradingCntry> |<TradingPostCode>|<TotalNoOfProperties>|<EstimatedPortfolioValue>|<TotalOutstandingMortgageBalance>|<TotalMontlyRentalIncome>|<TotalMonthlyMortgagePayment>|
    And Enter Personal Information for <LoanType>
      |Role  |Title  |DateOfAppointment  |Shareholding20OrGreater  |PercentShare  |Nationality  |MaritalStatus  |DOB  |NINumber  |PermanentRightToResideInsideUK  |FromBirth  |LengthOfResidencyYears  |LengthOfResidencyMonths  |PreviousTitle  |PreviousFirstName  |PreviousMiddleName  |PreviousLastName  |HomePhone  |MobileNumber  |MarketingPreference  |ByEmail  |ByTelephone  |BySms  |
      |<Role>|<Title>|<DateOfAppointment>|<Shareholding20OrGreater>|<PercentShare>|<Nationality>|<MaritalStatus>|<DOB>|<NINumber>|<PermanentRightToResideInsideUK>|<FromBirth>|<LengthOfResidencyYears>|<LengthOfResidencyMonths>|<PreviousTitle>|<PreviousFirstName>|<PreviousMiddleName>|<PreviousLastName>|<HomePhone>|<MobileNumber>|<MarketingPreference>|<ByEmail>|<ByTelephone>|<BySms>|
    And Enter Personal Continued Information for <LoanType>
      |ResidentialStatus  |MailingStreet  |City  |Country  |PostCode  |PreviousStreet  |PreviousCity  |PreviousCountry  |PreviousPostCode  |
      |<ResidentialStatus>|<MailingStreet>|<City>|<Country>|<PostCode>|<PreviousStreet>|<PreviousCity>|<PreviousCountry>|<PreviousPostCode>|
    And Enter Security Information
      |SecurityType  |SecurityEstimatedValue  |SecurityPurchasePrice  |SecurityLocation  |SecurityStreetAddress  |SecurityCity  |SecurityCountry  |SecurityPostCode  |SecurityPropertyType  |SecurityPropertyDescription  |SecurityUseOfProperty  |SecurityTenure  |YearsRemainingOnLease  |RentReviewDate  |ServiceCharge  |GroundRent  |
      |<SecurityType>|<SecurityEstimatedValue>|<SecurityPurchasePrice>|<SecurityLocation>|<SecurityStreetAddress>|<SecurityCity>|<SecurityCountry>|<SecurityPostCode>|<SecurityPropertyType>|<SecurityPropertyDescription>|<SecurityUseOfProperty>|<SecurityTenure>|<YearsRemainingOnLease>|<RentReviewDate>|<ServiceCharge>|<GroundRent>|
    And Enter Borrowers & Guarantors Information
      |BorrowerFirstName  |BorrowerLastName  |BorrowerEmail  |BorrowerMbNo  |BorrowerRole  |BorrowerRoleOnLoan  |
      |<BorrowerFirstName>|<BorrowerLastName>|<BorrowerEmail>|<BorrowerMbNo>|<BorrowerRole>|<BorrowerRoleOnLoan>|
    Then Review the Information for <LoanType>
      |LoanType  |LoanAmount  |LoanPurpose  |LoanTermMonths  |RepaymentTypes  |AmortizedTermMonths  |CaptialRepaymentHolidayMonths  |LegalBusinessName  |CRN  |DateOfIncorporation  |ApplicationType  |IndustryDoesBusinessBelongTo  |RegAddress  |RegCity  |RegCntry   |RegPostCode  |TradingAddress   |TradingCity  |TradingCntry   |TradingPostCode  |TotalNoOfProperties  |EstimatedPortfolioValue  |TotalOutstandingMortgageBalance  |TotalMontlyRentalIncome  |TotalMonthlyMortgagePayment  |Role   |Title  |DateOfAppointment  |shareholding20OrGreater  | PercentShare   |Nationality  |MaritalStatus  |DOB  |NINumber   |PermanentRightToResideInsideUK  |FromBirth  |LengthOfResidencyYears  |LengthOfResidencyMonths  |PreviousTitle  |PreviousFirstName  |PreviousMiddleName  |PreviousLastName  |HomePhone   |MobileNumber   |MarketingPreference  |ByEmail  |ByTelephone  |BySms  |ResidentialStatus   |MailingStreet  |City   |Country  |PostCode  |PreviousStreet  |PreviousCity  |PreviousCountry  |PreviousPostCode  |SecurityEstimatedValue  |SecurityPurchasePrice  |SecurityLocation  |SecurityStreetAddress  |SecurityCity  |SecurityCountry  |SecurityPostCode  |BorrowerFirstName  |BorrowerLastName  |BorrowerRoleOnLoan  |
      |<LoanType>|<LoanAmount>|<LoanPurpose>|<LoanTermMonths>|<RepaymentTypes>|<AmortizedTermMonths>|<CaptialRepaymentHolidayMonths>|<LegalBusinessName>|<CRN>|<DateOfIncorporation>|<ApplicationType>|<IndustryDoesBusinessBelongTo>|<RegAddress>|<RegCity>|<RegCntry> |<RegPostCode>|<TradingAddress> |<TradingCity>|<TradingCntry> |<TradingPostCode>|<TotalNoOfProperties>|<EstimatedPortfolioValue>|<TotalOutstandingMortgageBalance>|<TotalMontlyRentalIncome>|<TotalMonthlyMortgagePayment>|<Role> |<Title>|<DateOfAppointment>|<shareholding20OrGreater>| <PercentShare> |<Nationality>|<MaritalStatus>|<DOB>|<NINumber> |<PermanentRightToResideInsideUK>|<FromBirth>|<LengthOfResidencyYears>|<LengthOfResidencyMonths>|<PreviousTitle>|<PreviousFirstName>|<PreviousMiddleName>|<PreviousLastName>| <HomePhone>|<MobileNumber> |<MarketingPreference>|<ByEmail>|<ByTelephone>|<BySms>| <ResidentialStatus>|<MailingStreet>|<City> |<Country>|<PostCode>|<PreviousStreet>|<PreviousCity>|<PreviousCountry>|<PreviousPostCode>|<SecurityEstimatedValue>|<SecurityPurchasePrice>|<SecurityLocation>|<SecurityStreetAddress>|<SecurityCity>|<SecurityCountry>|<SecurityPostCode>|<BorrowerFirstName>|<BorrowerLastName>|<BorrowerRoleOnLoan>|

#    And Submit the Application

    Examples:
      |TestCaseId|LoanType                   |LoanAmount |LoanPurpose |LoanTermMonths  |RepaymentTypes        |AmortizedTermMonths  |CaptialRepaymentHolidayMonths  |LegalBusinessName    |CRN     |DateOfIncorporation|ApplicationType |IndustryDoesBusinessBelongTo |RegAddress             |RegCity        |RegCntry |RegPostCode|TradingAddress|TradingCity     |TradingCntry  |TradingPostCode|TotalNoOfProperties|EstimatedPortfolioValue|TotalOutstandingMortgageBalance|TotalMontlyRentalIncome|TotalMonthlyMortgagePayment|Role             |Title|DateOfAppointment|Shareholding20OrGreater|PercentShare |Nationality|MaritalStatus|DOB      |NINumber |PermanentRightToResideInsideUK|FromBirth|LengthOfResidencyYears|LengthOfResidencyMonths|PreviousTitle|PreviousFirstName|PreviousMiddleName|PreviousLastName| HomePhone|MobileNumber|MarketingPreference                                                              |ByEmail  |ByTelephone  |BySms|ResidentialStatus     |MailingStreet |City      |Country       |PostCode|PreviousStreet |PreviousCity      |PreviousCountry       |PreviousPostCode|SecurityType               |SecurityEstimatedValue|SecurityPurchasePrice|SecurityLocation|SecurityStreetAddress|SecurityCity|SecurityCountry|SecurityPostCode|SecurityPropertyType          |SecurityPropertyDescription|SecurityUseOfProperty|SecurityTenure|YearsRemainingOnLease|RentReviewDate|ServiceCharge|GroundRent|BorrowerFirstName |BorrowerLastName |BorrowerEmail|BorrowerMbNo |BorrowerRole     |BorrowerRoleOnLoan|
      |   TP-13  |Business Commercial Mortgage|1000       |Refinance   |120             |Interest Only         |100                  |90                             |    Testing          |12345678|1/1/2018           |Corporation     |Technology                   |Three Cherry Trees Lane|Hemel Hempstead|Herts    |HP2 7AH    |Arndale House |Manchester      |United Kingdom|M4 3AQ         |2                  |50000                  |1000                           |20000                  |1200                       |Business Partner |Test |5/9/2018         |Yes                    |30           |British    |Married      |5/1/2000 |1239087  |YES                           |Yes      |10                    |2                      |Mr           |Ajay             |Kumari            |Pant            |23123123  |72012390    |Yes please, send me information about Revver products and services               |Yes      |Yes          |Yes  |Owner with Mortgage   |Testing Street|Manchester|United Kingdom|M44AX   |Pre Street     |Pre City          |Germany               |M44EX           |Commercial - Industrial    |4000                  |2000                 |England         |Rohini               |Delhi       |India          |243003          |Office                        |Executive                  | Investment          |Freehold      |20                   |5/26/2019     |100          |200       |Andrew	        |Chatterton       |abc@gmail.com|07587278018  |Business Partner |	Guarantor      |
#      |   TP-2   |Business Commercial Mortgage|900        |Purchase    |100             |Principal & Interest  |110                  |95                             |    Quality          |12345688|12/14/2017         |Broker          |Agriculture                  |Three Cherry Trees     |Manchester     |UK       |HP2 7AQ    |City Center   |Hemel Hempstead |United Kingdom|M4 4AQ         |1                  |55000                  |1100                           |22000                  |1500                       |Company          |Ms   |6/10/2017        |No                     |20           |EU         |Single       |5/4/1981 |1239088  |NO                            |No       |2                     |1                      |Ms           |Raj              |Kumar             |Gupta           |23123129  |72012399    |No thanks, I do not want to receive information about Revver products or Services|No       |No           |No   |Owner without Mortgage|Mailing Street|London    |UK            |M44AQ   |Prev Street    |Prev City         |India                 |M44EQ           |Commercial - Agriculture   |2000                  |1000                 |Wales           |Queen Street         |Manchester  |United Kingdom |M44AQ           |Multi freehold (up to 4 units)|Apartments/Flats           | Owner Occupier      |Leasehold     |10                   |10/26/2019    |90           |120       |Manish Kumar      |Gupta            |xyz@gmail.com|07587278019  |Co-Owner         |	Co-Borrower    |



  @Test
  Scenario Outline: Login into Customer Portal Application with defafult credential and create a business commercial mortage process from mid
    Given Login into 'Customer Portal' application for the <TestCaseId>
    And Navigate to Existing Application
    And Enter Personal Information for <LoanType>
      |Role  |Title  |DateOfAppointment  |Shareholding20OrGreater  |PercentShare  |Nationality  |MaritalStatus  |DOB  |NINumber  |PermanentRightToResideInsideUK  |FromBirth  |LengthOfResidencyYears  |LengthOfResidencyMonths  |PreviousTitle  |PreviousFirstName  |PreviousMiddleName  |PreviousLastName  |HomePhone  |MobileNumber  |MarketingPreference  |ByEmail  |ByTelephone  |BySms  |
      |<Role>|<Title>|<DateOfAppointment>|<Shareholding20OrGreater>|<PercentShare>|<Nationality>|<MaritalStatus>|<DOB>|<NINumber>|<PermanentRightToResideInsideUK>|<FromBirth>|<LengthOfResidencyYears>|<LengthOfResidencyMonths>|<PreviousTitle>|<PreviousFirstName>|<PreviousMiddleName>|<PreviousLastName>|<HomePhone>|<MobileNumber>|<MarketingPreference>|<ByEmail>|<ByTelephone>|<BySms>|
    And Enter Personal Continued Information for <LoanType>
      |ResidentialStatus  |MailingStreet  |City  |Country  |PostCode  |PreviousStreet  |PreviousCity  |PreviousCountry  |PreviousPostCode  |
      |<ResidentialStatus>|<MailingStreet>|<City>|<Country>|<PostCode>|<PreviousStreet>|<PreviousCity>|<PreviousCountry>|<PreviousPostCode>|
    And Enter Security Information
      |SecurityType  |SecurityEstimatedValue  |SecurityPurchasePrice  |SecurityLocation  |SecurityStreetAddress  |SecurityCity  |SecurityCountry  |SecurityPostCode  |SecurityPropertyType  |SecurityPropertyDescription  |SecurityUseOfProperty  |SecurityTenure  |YearsRemainingOnLease  |RentReviewDate  |ServiceCharge  |GroundRent  |
      |<SecurityType>|<SecurityEstimatedValue>|<SecurityPurchasePrice>|<SecurityLocation>|<SecurityStreetAddress>|<SecurityCity>|<SecurityCountry>|<SecurityPostCode>|<SecurityPropertyType>|<SecurityPropertyDescription>|<SecurityUseOfProperty>|<SecurityTenure>|<YearsRemainingOnLease>|<RentReviewDate>|<ServiceCharge>|<GroundRent>|
    And Enter Borrowers & Guarantors Information
      |BorrowerFirstName  |BorrowerLastName  |BorrowerEmail  |BorrowerMbNo  |BorrowerRole  |BorrowerRoleOnLoan  |
      |<BorrowerFirstName>|<BorrowerLastName>|<BorrowerEmail>|<BorrowerMbNo>|<BorrowerRole>|<BorrowerRoleOnLoan>|
    Then Review the Information for <LoanType>
      |LoanType  |LoanAmount  |LoanPurpose  |LoanTermMonths  |RepaymentTypes  |AmortizedTermMonths  |CaptialRepaymentHolidayMonths  |LegalBusinessName  |CRN  |DateOfIncorporation  |ApplicationType  |IndustryDoesBusinessBelongTo  |RegAddress  |RegCity  |RegCntry   |RegPostCode  |TradingAddress   |TradingCity  |TradingCntry   |TradingPostCode  |TotalNoOfProperties  |EstimatedPortfolioValue  |TotalOutstandingMortgageBalance  |TotalMontlyRentalIncome  |TotalMonthlyMortgagePayment  |Role   |Title  |DateOfAppointment  |shareholding20OrGreater  | PercentShare   |Nationality  |MaritalStatus  |DOB  |NINumber   |PermanentRightToResideInsideUK  |FromBirth  |LengthOfResidencyYears  |LengthOfResidencyMonths  |PreviousTitle  |PreviousFirstName  |PreviousMiddleName  |PreviousLastName  |HomePhone   |MobileNumber   |MarketingPreference  |ByEmail  |ByTelephone  |BySms  |ResidentialStatus   |MailingStreet  |City   |Country  |PostCode  |PreviousStreet  |PreviousCity  |PreviousCountry  |PreviousPostCode  |SecurityEstimatedValue  |SecurityPurchasePrice  |SecurityLocation  |SecurityStreetAddress  |SecurityCity  |SecurityCountry  |SecurityPostCode  |BorrowerFirstName  |BorrowerLastName  |BorrowerRoleOnLoan  |
      |<LoanType>|<LoanAmount>|<LoanPurpose>|<LoanTermMonths>|<RepaymentTypes>|<AmortizedTermMonths>|<CaptialRepaymentHolidayMonths>|<LegalBusinessName>|<CRN>|<DateOfIncorporation>|<ApplicationType>|<IndustryDoesBusinessBelongTo>|<RegAddress>|<RegCity>|<RegCntry> |<RegPostCode>|<TradingAddress> |<TradingCity>|<TradingCntry> |<TradingPostCode>|<TotalNoOfProperties>|<EstimatedPortfolioValue>|<TotalOutstandingMortgageBalance>|<TotalMontlyRentalIncome>|<TotalMonthlyMortgagePayment>|<Role> |<Title>|<DateOfAppointment>|<shareholding20OrGreater>| <PercentShare> |<Nationality>|<MaritalStatus>|<DOB>|<NINumber> |<PermanentRightToResideInsideUK>|<FromBirth>|<LengthOfResidencyYears>|<LengthOfResidencyMonths>|<PreviousTitle>|<PreviousFirstName>|<PreviousMiddleName>|<PreviousLastName>| <HomePhone>|<MobileNumber> |<MarketingPreference>|<ByEmail>|<ByTelephone>|<BySms>| <ResidentialStatus>|<MailingStreet>|<City> |<Country>|<PostCode>|<PreviousStreet>|<PreviousCity>|<PreviousCountry>|<PreviousPostCode>|<SecurityEstimatedValue>|<SecurityPurchasePrice>|<SecurityLocation>|<SecurityStreetAddress>|<SecurityCity>|<SecurityCountry>|<SecurityPostCode>|<BorrowerFirstName>|<BorrowerLastName>|<BorrowerRoleOnLoan>|

    Examples:
      |TestCaseId|LoanType                   |LoanAmount |LoanPurpose |LoanTermMonths  |RepaymentTypes        |AmortizedTermMonths  |CaptialRepaymentHolidayMonths  |LegalBusinessName    |CRN     |DateOfIncorporation|ApplicationType |IndustryDoesBusinessBelongTo |RegAddress             |RegCity        |RegCntry |RegPostCode|TradingAddress|TradingCity     |TradingCntry  |TradingPostCode|TotalNoOfProperties|EstimatedPortfolioValue|TotalOutstandingMortgageBalance|TotalMontlyRentalIncome|TotalMonthlyMortgagePayment|Role             |Title|DateOfAppointment|Shareholding20OrGreater|PercentShare |Nationality|MaritalStatus|DOB      |NINumber |PermanentRightToResideInsideUK|FromBirth|LengthOfResidencyYears|LengthOfResidencyMonths|PreviousTitle|PreviousFirstName|PreviousMiddleName|PreviousLastName| HomePhone|MobileNumber|MarketingPreference                                                              |ByEmail  |ByTelephone  |BySms|ResidentialStatus     |MailingStreet |City      |Country       |PostCode|PreviousStreet |PreviousCity      |PreviousCountry       |PreviousPostCode|SecurityType               |SecurityEstimatedValue|SecurityPurchasePrice|SecurityLocation|SecurityStreetAddress|SecurityCity|SecurityCountry|SecurityPostCode|SecurityPropertyType          |SecurityPropertyDescription|SecurityUseOfProperty|SecurityTenure|YearsRemainingOnLease|RentReviewDate|ServiceCharge|GroundRent|BorrowerFirstName |BorrowerLastName |BorrowerEmail|BorrowerMbNo |BorrowerRole     |BorrowerRoleOnLoan|
      |   TP-13  |Business Commercial Mortgage|1000       |Refinance   |120             |Interest Only         |100                  |90                             |    Testing          |12345678|1/1/2018           |Corporation     |Technology                   |Three Cherry Trees Lane|Hemel Hempstead|Herts    |HP2 7AH    |Arndale House |Manchester      |United Kingdom|M4 3AQ         |2                  |50000                  |1000                           |20000                  |1200                       |Business Partner |Test |5/9/2018         |Yes                    |30           |British    |Married      |5/1/2000 |1239087  |YES                           |Yes      |10                    |2                      |Mr           |Ajay             |Kumari            |Pant            |23123123  |72012390    |Yes please, send me information about Revver products and services               |Yes      |Yes          |Yes  |Owner with Mortgage   |Testing Street|Manchester|United Kingdom|M44AX   |Pre Street     |Pre City          |Germany               |M44EX           |Commercial - Industrial    |4000                  |2000                 |England         |Rohini               |Delhi       |India          |243003          |Office                        |Executive                  | Investment          |Freehold      |20                   |5/26/2019     |100          |200       |Andrew	        |Chatterton       |abc@gmail.com|07587278018  |Business Partner |	Guarantor      |