Feature: Access the URSA Bank application and create a application for Business Commercial Mortgage

  @Regression
Scenario Outline: Login into Customer Portal Application with defafult credential and create a business commercial mortage process using Data Driven
Given Login into 'Customer Portal' application for the <TestCaseId>

When Navigate to Marketplace
And Apply for <LoanType>
And Enter Eligibility Information for <LoanType>
|LoanAmount  |LoanPurpose  |
|<LoanAmount>|<LoanPurpose>|
And Enter Business Information
|LegalBusinessName  |CRN  |DateOfIncorporation  |ApplicationType  |IndustryDoesBusinessBelongTo  |RegAddress  |RegCity  |RegCntry   |RegPostCode  |TradingAddress   |TradingCity  |TradingCntry   |TradingPostCode  |TotalNoOfProperties  |EstimatedPortfolioValue  |TotalOutstandingMortgageBalance  |TotalMontlyRentalIncome  |TotalMonthlyMortgagePayment  |
|<LegalBusinessName>|<CRN>|<DateOfIncorporation>|<ApplicationType>|<IndustryDoesBusinessBelongTo>|<RegAddress>|<RegCity>|<RegCntry> |<RegPostCode>|<TradingAddress> |<TradingCity>|<TradingCntry> |<TradingPostCode>|<TotalNoOfProperties>|<EstimatedPortfolioValue>|<TotalOutstandingMortgageBalance>|<TotalMontlyRentalIncome>|<TotalMonthlyMortgagePayment>|
And Enter Personal Information for <LoanType>
|Role  |Title  |DateOfAppointment  |PercentShare  |Nationality  |MaritalStatus  |DOB  |NINumber  |PermanentRightToResideInsideUK  |FromBirth  |LengthOfResidencyYears  |LengthOfResidencyMonths  |PreviousTitle  |PreviousFirstName  |PreviousMiddleName  |PreviousLastName  |HomePhone  |MobileNumber  |MarketingPreference  |
|<Role>|<Title>|<DateOfAppointment>|<PercentShare>|<Nationality>|<MaritalStatus>|<DOB>|<NINumber>|<PermanentRightToResideInsideUK>|<FromBirth>|<LengthOfResidencyYears>|<LengthOfResidencyMonths>|<PreviousTitle>|<PreviousFirstName>|<PreviousMiddleName>|<PreviousLastName>|<HomePhone>|<MobileNumber>|<MarketingPreference>|
And Enter Personal Continued Information for <LoanType>
|ResidentialStatus  |MailingStreet  |City  |Country  |PostCode  |PreviousStreet  |PreviousCity  |PreviousCountry  |PreviousPostCode  |
|<ResidentialStatus>|<MailingStreet>|<City>|<Country>|<PostCode>|<PreviousStreet>|<PreviousCity>|<PreviousCountry>|<PreviousPostCode>|
And Enter Security Information
|SecurityType  |SecurityEstimatedValue  |SecurityPurchasePrice  |SecurityLocation  |SecurityStreetAddress  |SecurityCity  |SecurityCountry  |SecurityPostCode  |SecurityPropertyType  |SecurityPropertyDescription  |SecurityUseOfProperty  |SecurityTenure  |YearsRemainingOnLease  |RentReviewDate  |ServiceCharge  |GroundRent  |
|<SecurityType>|<SecurityEstimatedValue>|<SecurityPurchasePrice>|<SecurityLocation>|<SecurityStreetAddress>|<SecurityCity>|<SecurityCountry>|<SecurityPostCode>|<SecurityPropertyType>|<SecurityPropertyDescription>|<SecurityUseOfProperty>|<SecurityTenure>|<YearsRemainingOnLease>|<RentReviewDate>|<ServiceCharge>|<GroundRent>|
And Enter Borrowers & Guarantors Information
|BorrowerFirstName  |BorrowerLastName  |BorrowerEmail  |BorrowerMbNo  |BorrowerRole  |BorrowerRoleOnLoan  |
|<BorrowerFirstName>|<BorrowerLastName>|<BorrowerEmail>|<BorrowerMbNo>|<BorrowerRole>|<BorrowerRoleOnLoan>|
And Review the Information for <LoanType>
|LoanType  |LoanAmount  |LoanPurpose  |LegalBusinessName  |CRN  |DateOfIncorporation  |ApplicationType  |IndustryDoesBusinessBelongTo  |RegAddress  |RegCity  |RegCntry   |RegPostCode  |TradingAddress   |TradingCity  |TradingCntry   |TradingPostCode  |Role   |Title  |DateOfAppointment  |PercentShare   |Nationality  |MaritalStatus  |DOB  |NINumber   |HomePhone  |MobileNumber   |MailingStreet  |City   |Country  |PostCode   |SecurityType  |SecurityName  |SecurityEstimatedValue  |SecurityStreetAddress  |SecurityCity  |SecurityCountry  |SecurityPostCode  |SecuirtyPropertyType  |SecurityYearBuilt  |SecurityCondition  |SecurityTenure  |BorrowerFirstName  |BorrowerLastName  |BorrowerEmail  |BorrowerMbNo  |BorrowerRole  |BorrowerRoleOnLoan  |
|<LoanType>|<LoanAmount>|<LoanPurpose>|<LegalBusinessName>|<CRN>|<DateOfIncorporation>|<ApplicationType>|<IndustryDoesBusinessBelongTo>|<RegAddress>|<RegCity>|<RegCntry> |<RegPostCode>|<TradingAddress> |<TradingCity>|<TradingCntry> |<TradingPostCode>|<Role> |<Title>|<DateOfAppointment>|<PercentShare> |<Nationality>|<MaritalStatus>|<DOB>|<NINumber> |<HomePhone>|<MobileNumber> |<MailingStreet>|<City> |<Country>|<PostCode> |<SecurityType>|<SecurityName>|<SecurityEstimatedValue>|<SecurityStreetAddress>|<SecurityCity>|<SecurityCountry>|<SecurityPostCode>|<SecuirtyPropertyType>|<SecurityYearBuilt>|<SecurityCondition>|<SecurityTenure>|<BorrowerFirstName>|<BorrowerLastName>|<BorrowerEmail>|<BorrowerMbNo>|<BorrowerRole>|<BorrowerRoleOnLoan>|

Examples:
  |TestCaseId|LoanType                                  |LoanAmount |LoanPurpose |LongTermMonths  |RepaymentTypes  |AmortizedTermMonths  |CaptialRepaymentHolidayMonths  |LongTermMonths  |LegalBusinessName|CRN     |DateOfIncorporation|ApplicationType |IndustryDoesBusinessBelongTo |RegAddress             |RegCity        |RegCntry |RegPostCode|TradingAddress|TradingCity|TradingCntry  |TradingPostCode|TotalNoOfProperties|EstimatedPortfolioValue|TotalOutstandingMortgageBalance|TotalMontlyRentalIncome|TotalMonthlyMortgagePayment|Role             |Title|DateOfAppointment|PercentShare |Nationality|MaritalStatus|DOB      |NINumber |PermanentRightToResideInsideUK|FromBirth|LengthOfResidencyYears|LengthOfResidencyMonths|PreviousTitle|PreviousFirstName|PreviousMiddleName|PreviousLastName| HomePhone|MobileNumber|MarketingPreference                                                              |ResidentialStatus  |MailingStreet |City      |Country       |PostCode|PreviousStreet |PreviousCity      |PreviousCountry       |PreviousPostCode|SecurityType|SecurityEstimatedValue|SecurityPurchasePrice|SecurityLocation|SecurityStreetAddress|SecurityCity|SecurityCountry|SecurityPostCode|SecurityPropertyType|SecurityPropertyDescription|SecurityUseOfProperty|SecurityTenure|YearsRemainingOnLease|RentReviewDate|ServiceCharge|GroundRent|BorrowerFirstName |BorrowerLastName |BorrowerEmail|BorrowerMbNo |BorrowerRole     |BorrowerRoleOnLoan|
  |   TP-13  |Individual/Sole Trader Commercial Mortgage|1000       |Refinance   |120             |Interest Only   |100                  |90                             |    20          |Testing          |12345678|1/1/2019           |Corporation     |Technology                   |Three Cherry Trees Lane|Hemel Hempstead|Herts    |HP2 7AH    |Arndale House |Manchester |United Kingdom|M4 3AQ         |2                  |50000                  |1000                           |20000                  |1200                       |Business Partner |Test |5/9/2018         |30           |British    |Married      |5/1/2000 |1239087  |YES                           |Yes      |10                    |2                      |Mr           |Ajay             |Kumari            |Pant            |23123123  |72012390    |No thanks, I do not want to receive information about Revver products or Services|Owner with Mortgage|Testing Street|Manchester|United Kingdom|M44AX   |Pre Street     |Pre City          |Germany               |M44EX           |Industrial  |4000                  |2000                 |England         |Rohini               |Delhi       |India          |243003          |Office              |Executive                  | Investment          |Freehold      |20                   |5/26/2019     |100          |200       |Andrew	          |Chatterton       |abc@gmail.com|	07587278018	|Business Partner |	Guarantor        |




  @Test
  Scenario Outline: Login into Customer Portal Application with defafult credential and create a business commercial mortage process using 1
    Given Login into 'Customer Portal' application for the <TestCaseId>
    And Navigate to Existing Application
    And Enter Security Information
      |SecurityType  |SecurityEstimatedValue  |SecurityPurchasePrice  |SecurityLocation  |SecurityStreetAddress  |SecurityCity  |SecurityCountry  |SecurityPostCode  |SecurityPropertyType  |SecurityPropertyDescription  |SecurityUseOfProperty  |SecurityTenure  |YearsRemainingOnLease  |RentReviewDate  |ServiceCharge  |GroundRent  |
      |<SecurityType>|<SecurityEstimatedValue>|<SecurityPurchasePrice>|<SecurityLocation>|<SecurityStreetAddress>|<SecurityCity>|<SecurityCountry>|<SecurityPostCode>|<SecurityPropertyType>|<SecurityPropertyDescription>|<SecurityUseOfProperty>|<SecurityTenure>|<YearsRemainingOnLease>|<RentReviewDate>|<ServiceCharge>|<GroundRent>|
    And Enter Borrowers & Guarantors Information
      |BorrowerFirstName  |BorrowerLastName  |BorrowerEmail  |BorrowerMbNo  |BorrowerRole  |BorrowerRoleOnLoan  |
      |<BorrowerFirstName>|<BorrowerLastName>|<BorrowerEmail>|<BorrowerMbNo>|<BorrowerRole>|<BorrowerRoleOnLoan>|
    And Review the Information for <LoanType>
      |LoanType  |LoanAmount  |LoanPurpose  |LegalBusinessName  |CRN  |DateOfIncorporation  |ApplicationType  |IndustryDoesBusinessBelongTo  |RegAddress  |RegCity  |RegCntry   |RegPostCode  |TradingAddress   |TradingCity  |TradingCntry   |TradingPostCode  |Role   |Title  |DateOfAppointment  |PercentShare   |Nationality  |MaritalStatus  |DOB  |NINumber   |HomePhone  |MobileNumber   |MailingStreet  |City   |Country  |PostCode   |SecurityType  |SecurityName  |SecurityEstimatedValue  |SecurityStreetAddress  |SecurityCity  |SecurityCountry  |SecurityPostCode  |SecuirtyPropertyType  |SecurityYearBuilt  |SecurityCondition  |SecurityTenure  |BorrowerFirstName  |BorrowerLastName  |BorrowerEmail  |BorrowerMbNo  |BorrowerRole  |BorrowerRoleOnLoan  |
      |<LoanType>|<LoanAmount>|<LoanPurpose>|<LegalBusinessName>|<CRN>|<DateOfIncorporation>|<ApplicationType>|<IndustryDoesBusinessBelongTo>|<RegAddress>|<RegCity>|<RegCntry> |<RegPostCode>|<TradingAddress> |<TradingCity>|<TradingCntry> |<TradingPostCode>|<Role> |<Title>|<DateOfAppointment>|<PercentShare> |<Nationality>|<MaritalStatus>|<DOB>|<NINumber> |<HomePhone>|<MobileNumber> |<MailingStreet>|<City> |<Country>|<PostCode> |<SecurityType>|<SecurityName>|<SecurityEstimatedValue>|<SecurityStreetAddress>|<SecurityCity>|<SecurityCountry>|<SecurityPostCode>|<SecuirtyPropertyType>|<SecurityYearBuilt>|<SecurityCondition>|<SecurityTenure>|<BorrowerFirstName>|<BorrowerLastName>|<BorrowerEmail>|<BorrowerMbNo>|<BorrowerRole>|<BorrowerRoleOnLoan>|

    Examples:
      |TestCaseId|LoanType                                  |LoanAmount |LoanPurpose |LongTermMonths  |RepaymentTypes  |AmortizedTermMonths  |CaptialRepaymentHolidayMonths  |LongTermMonths  |LegalBusinessName|CRN     |DateOfIncorporation|ApplicationType |IndustryDoesBusinessBelongTo |RegAddress             |RegCity        |RegCntry |RegPostCode|TradingAddress|TradingCity|TradingCntry  |TradingPostCode|TotalNoOfProperties|EstimatedPortfolioValue|TotalOutstandingMortgageBalance|TotalMontlyRentalIncome|TotalMonthlyMortgagePayment|Role             |Title|DateOfAppointment|PercentShare |Nationality|MaritalStatus|DOB      |NINumber |PermanentRightToResideInsideUK|FromBirth|LengthOfResidencyYears|LengthOfResidencyMonths|PreviousTitle|PreviousFirstName|PreviousMiddleName|PreviousLastName| HomePhone|MobileNumber|MarketingPreference                                                              |ResidentialStatus  |MailingStreet |City      |Country       |PostCode|PreviousStreet |PreviousCity      |PreviousCountry       |PreviousPostCode|SecurityType|SecurityEstimatedValue|SecurityPurchasePrice|SecurityLocation|SecurityStreetAddress|SecurityCity|SecurityCountry|SecurityPostCode|SecurityPropertyType|SecurityPropertyDescription|SecurityUseOfProperty|SecurityTenure|YearsRemainingOnLease|RentReviewDate|ServiceCharge|GroundRent|BorrowerFirstName |BorrowerLastName |BorrowerEmail|BorrowerMbNo |BorrowerRole     |BorrowerRoleOnLoan|
      |   TP-13  |Individual/Sole Trader Commercial Mortgage|1000       |Refinance   |120             |Interest Only   |100                  |90                             |    20          |Testing          |12345678|1/1/2019           |Corporation     |Technology                   |Three Cherry Trees Lane|Hemel Hempstead|Herts    |HP2 7AH    |Arndale House |Manchester |United Kingdom|M4 3AQ         |2                  |50000                  |1000                           |20000                  |1200                       |Business Partner |Test |5/9/2018         |30           |British    |Married      |5/1/2000 |1239087  |YES                           |Yes      |10                    |2                      |Mr           |Ajay             |Kumari            |Pant            |23123123  |72012390    |No thanks, I do not want to receive information about Revver products or Services|Owner with Mortgage|Testing Street|Manchester|United Kingdom|M44AX   |Pre Street     |Pre City          |Germany               |M44EX           |Industrial  |4000                  |2000                 |England         |Rohini               |Delhi       |India          |243003          |Office              |Executive                  | Investment          |Freehold      |20                   |5/26/2019     |100          |200       |Andrew	          |Chatterton       |abc@gmail.com|	07587278018	|Business Partner |	Guarantor        |